server:
  port: 80

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://120.77.243.1:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: root